apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.minimal.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.minimal.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: email_archive_django
            - name: MARIADB_PASSWORD
              value: passwd
            - name: MARIADB_ROOT_PASSWORD
              value: example
            - name: MARIADB_USER
              value: user
          image: mariadb:latest
          livenessProbe:
            exec:
              command:
                - mariadb -u$MARIADB_USER -p$MARIADB_PASSWORD -e 'SELECT 1'
            failureThreshold: 12
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: eonvelope-db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-claim0
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
