# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black
        args: [--config, tools/black_config]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--config, tools/ruff.toml]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.29.1
    hooks:
      - id: django-upgrade
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        args: [--configuration, tools/djlintrc]
      - id: djlint-django
        args: [--configuration, tools/djlintrc]
  - repo: https://github.com/python-poetry/poetry
    rev: 2.3.2
    hooks:
      - id: poetry-lock
      - id: poetry-check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--config, tools/.codespellrc]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args: [--config, tools/.hadolint.yaml]
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.14
    hooks:
      - id: biome-check
        args: [--config-path, tools/biome.json]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.8.2
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/PyCQA/doc8
    rev: v2.0.0
    hooks:
      - id: doc8
        args: [--config, tools/doc8.ini]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: [--config, tools/.markdownlint.yml]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: validate_templates
        name: Validate template files
        entry: poetry run python3 manage.py validate_templates
        pass_filenames: false
        language: system
        types: [html]
  - repo: local
    hooks:
      - id: validate_openapi_schema
        name: Validate openapi schema documentation
        entry: poetry run python3 manage.py spectacular --validate --fail-on-warn > /dev/null
        pass_filenames: false
        language: system
        files: (src/api/.*\.py|poetry.lock)
  - repo: https://github.com/timo-reymann/gitlab-ci-verify
    rev: v2.9.2
    hooks:
      - id: gitlab-ci-verify
        args: [--gitlab-base-url, gitlab.com, --severity, warning]
