version: '0.0.1'

services:
  db:
    image: mariadb:latest
    volumes:
      - /main/Emailkasten/test/mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=email_archive_django
      - MARIADB_USER=user
      - MARIADB_PASSWORD=passwd
      - MARIADB_ROOT_PASSWORD=example
    container_name: emailkasten_db
    restart: unless-stopped

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 9999:8080

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /main/Emailkasten/test/archive:/mnt/archive
      - /main/Emailkasten/test/log:/var/log
    ports:
      - 1122:8000
    environment:
      - DB_NAME=email_archive_django
      - DB_USER=user
      - DB_PASSWORD=passwd
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    depends_on:
      - db
