version: '0.0.1'

services:
  db:
    image: mariadb:latest
    volumes:
      - /root/Emailkasten/test/mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=email_archive_django
      - MARIADB_USER=user
      - MARIADB_PASSWORD=passwd
      - MARIADB_ROOT_PASSWORD=example
    container_name: emailkasten_db
    restart: unless-stopped

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 9999:8080

  web:
    build: .
    volumes:
      - /main/Emailkasten/test/mnt:/code
      - /main/Emailkasten/test/attachments:/mnt/attachments
      - /main/Emailkasten/test/eml:/mnt/eml
    ports:
      - 1122:8000
    environment:
      - DB_NAME=email_archive_django
      - DB_USER=user
      - DB_PASSWORD=passwd
    depends_on:
      - db