apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker/docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "1122"
      port: 1122
      targetPort: 443
  selector:
    io.kompose.service: web
