services:
  db:
    image: mariadb:latest
    container_name: emailkasten-db
    volumes:
      - /path/to/emailkasten/mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=email_archive_django # must match web:DATABASE_NAME
      - MARIADB_USER=user # must match web:DATABASE_USER
      - MARIADB_PASSWORD=passwd # must match web:DATABASE_PASSWORD
      - MARIADB_ROOT_PASSWORD=example
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mariadb -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  web:
    image: emailkasten-debug
    container_name: emailkasten-web
    volumes:
      - /path/to/emailkasten/archive:/mnt/archive
      - /path/to/emailkasten/log:/var/log/emailkasten
    ports:
      - 1122:443
    environment:
    # mandatory
      - DATABASE=email_archive_django # must match db:MARIADB_DATABASE
      - DATABASE_USER=user # must match db:MARIADB_USER
      - DATABASE_PASSWORD=passwd # must match db:MARIADB_PASSWORD
      - DATABASE_TYPE=mysql # possible values: mysql, postgresql, sqlite3; must match the database type of the db container
      - DJANGO_SUPERUSER_PASSWORD=rootqwertz123
      - SECRET_KEY='PLEASE_REPLACE_ME_WITH_THE_OUTPUT_OF_A_STRONG_RANDOM_GENERATOR!'
      - ALLOWED_HOSTS=localhost,emailkasten.mydomain.tld # all allowed host URLs separated by ,
    # optional
      - REGISTRATION_ENABLED=False
      - STRICT_PASSWORDS=True
      - MFA_TRUST_ENABLED=True
      - MFA_TOTP_TOLERANCE=1
      - APP_LOG_LEVEL=INFO
      - DJANGO_LOG_LEVEL=INFO
      - CELERY_LOG_LEVEL=INFO
      - AMQP_LOG_LEVEL=INFO
      - LOGFILE_MAXSIZE=10485760
      - LOGFILE_BACKUP_NUMBER=5
      - CACHE_MIDDLEWARE_SECONDS=600
      - SECURE_HSTS_SECONDS=31536000
      - DISALLOWED_USER_AGENTS=.*Trident/.* # collection of regex patterns for user agent strings that must not visit any page of this Emailkasten instance seperated by ,
      - CSRF_TRUSTED_ORIGINS=https://subdomain.mydomain.tld # all URLs that can be trusted with unsafe requests separated by , . Must start with http:// or https:// each.
      - CSRF_COOKIE_AGE=31449600
      - CSRF_COOKIE_SAMESITE=Lax # the samesite value on the csrf-cookie. See https://docs.djangoproject.com/en/5.1/ref/settings/#session-cookie-samesite for more info.
      - LANGUAGE_COOKIE_AGE=2419200
      - LANGUAGE_COOKIE_SAMESITE=None  # the samesite value on the language-cookie. See https://docs.djangoproject.com/en/5.1/ref/settings/#session-cookie-samesite for more info.
      - SESSION_COOKIE_AGE=2419200
      - SESSION_EXPIRE_AT_BROWSER_CLOSE=False
      - SESSION_COOKIE_SAMESITE=Lax  # the samesite value on the session-cookie. See https://docs.djangoproject.com/en/5.1/ref/settings/#session-cookie-samesite for more info.
      - GUNICORN_WORKER_NUMBER=2
      - ENABLE_FLOWER=False
      - DEBUG=False
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
