preview = false
fix = false
unsafe-fixes = false
target-version = "py311"
line-length = 100
extend-exclude = ["*migrations*", "docs", "validation", "docker", ".vscode", ".pytest_cache", "__pycache__"]
output-format = "full"

[lint]

select = [
  "A",    # flake8-builtins
  "ANN",  # flake8-type-annotations
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "COM",  # flake8-commas
  "D",    # pydocstyle
  "DJ",   # flake8-django
  "DOC",  # pydoclint
  "DTZ",  # flake8-datetimez
  "E4",   # pycodestyle default
  "E7",   # pycodestyle default
  "E9",   # pycodestyle default
  "ERA",  # flake8-eradicate
  "EXE",  # flake8-executable
  "F",    # pyflakes
  "FA",   # flake8-future-annotations
  "FBT",  # flake8-boolean-trap
  "FLY",  # pyflint
  "FURB", # refurb
  "G",    # flake8-logging-format
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "INP",  # flake8-no-pep420
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
#  "N",    # pep8-naming, disabled while still using Javastyle naming
  "PERF", # perflint
  "PIE",  # flake8-pie
  "PL",   # pylint
  "PT",   # flake8-pytest-style
  "Q",    # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # ruff
  "S",    # flake8-bandit
  "SIM",  # flake8-simpify
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "T20",  # flake8-print
  "T10", # flake8-debugger
  "TC",  # flake8-type-checking
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]
ignore = [
  "COM812", # trailing comma, redundant with `black`
  "D203",   # no blank line before class docstring
  "D401",   # docstring does not need to be imperative
  "D417",  # must be disabled for google style docs
  "ISC003",  # prefer explicit string concat over implicit concat
  "PLR09",   # we have our own complexity rules
  "TRY003",  # long exception messages from `tryceratops`
]
external = [ "WPS" ]

mccabe.max-complexity = 6
[lint.pydocstyle]
convention = "google"

# Plugin configs:
[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

# [lint.flake8-copyright]
# notice-rgx =

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
parametrize-values-row-type = "tuple"
parametrize-values-type = "list"

[lint.per-file-ignores]
"test/*.py" = [
  "S101", # asserts
]
