deploy-pages:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - echo "Skipping dependency installation."
  script:
    - echo "Pages are deployed to $CI_PAGES_URL ."
  pages:
    publish: .gitlab/pages
